# Generated by Django 2.2.3 on 2019-07-17 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='submission',
            field=models.DateField(default=datetime.datetime(2019, 7, 18, 2, 33, 11, 178701), verbose_name='submitted date'),
        ),
    ]
