# Generated by Django 2.2.3 on 2019-07-17 20:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190718_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='submission',
            field=models.DateField(default=datetime.datetime(2019, 7, 17, 20, 50, 51, 346503, tzinfo=utc), verbose_name='submitted date'),
        ),
    ]
