# Generated by Django 2.2.3 on 2019-07-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('First_Name', models.TextField(max_length=20)),
                ('Middle_Name', models.TextField(max_length=20)),
                ('Last_Name', models.TextField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Contact', models.BigIntegerField(max_length=10)),
            ],
        ),
    ]
